# Generated by Django 5.1.1 on 2025-09-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('select_product', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Mob_num', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
